name: Global - Schedule - E2E - UAT 🧪

on:
  schedule:
  # every weekdays at 7:15 AM
  - cron: "15 7 * * 1-5"
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: env to runs on
        default: all
        options:
        - all
        - dev
        - uat
        - prep


jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - environment: dev
            config-file: scheduled-dev.config.ts
          - environment: uat
            config-file: scheduled-uat.config.ts
          - environment: prep
            config-file: scheduled-prep.config.ts
    steps:
      - name: ✅ Cypress E2E
        run: |
          echo ${{matrix.environment}} and ${{matrix.config-file}}
    
