name: Global - Schedule - E2E - UAT 🧪

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: env to runs on
        default: all
        options:
        - all
        - dev
        - uat
        - prep


jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - environment: dev
            config-file: scheduled-dev.config.ts
          - environment: uat
            config-file: scheduled-uat.config.ts
          - environment: prep
            config-file: scheduled-prep.config.ts
    steps:
      - name: early return
        if: ${{ inputs.environment && inputs.environment != 'all' && matrix.environment != inputs.environment }}
        run: exit 1

      - name: ✅ Cypress E2E
        run: |
          echo ${{matrix.environment}} and ${{matrix.config-file}}

      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: run custom action
        uses: ./.github/actions/test
        with:
          config-file: ./${{matrix.config-file}}
    
